removeAllWeapons player;
removeGoggles player;
removeHeadgear player;
removeVest player;
removeVest player;
removeUniform player;
removeAllAssignedItems player;
clearAllItemsFromBackpack player;
removeBackpack player;
player setUnitLoadout(player getVariable["saved_loadout", []]);